### ISSUE TITLE
Not really an issue. I'd like to add a space right after an emoji. Possible?

### ISSUE THREAD

**Issue by qbiz123** [kurdt94/basic_emoji_tinyMCE#1]
Hi

Right now there's no auto space right after an emoji. So if someone places it in the editor and then starts typing it will look like this:

🙂dfdsfdsfds

If it had a space users wouldn't have to use the space bar. TBHWY, most users forget to push the space bar for whatever reason. What can I add to the script to have a space right after an emoji from the get-go so that it would look like this: 🙂 dfdsfdsfds? Thanks!!

**Comment by kurdt94** [comment]
plugin.js , line 201 :  editor.insertContent(src);
change to something like

```
src += "&nbsp;";
editor.insertContent(src);
```
did not test this, since I no longer use the plugin.

**Comment by qbiz123** [comment]
Thank you. It works. I am still using their old version. It's light and does the job. Again, thank you.
